### ISSUE TITLE
[Clarification]: package.json lint-staged

### ISSUE THREAD

**Issue by ticklepoke** [alex996/react-css-spinners#7]
Should your lint-staged configuration in the package.json include .ts extensions?
Here's an example:

```
...
 "lint-staged": { 
    "*.{ts, js}": [
      "npm run lint:fix",
      "npm run test:staged",
      "git add"
    ]
  },
...
```

**Comment by alex996** [comment]
Good call. It should be working now.

**Comment by ticklepoke** [comment]
Hey Alex, I'm not sure if regex is supported for the keys. I was not able to detect tx files while committing. One work around I used was to have duplicate code blocks for each extension.
```
 "lint-staged": {
    "*.js": [
      "npm run lint:fix",
      "npm run test:staged",
      "git add"
    ],
    "*.ts": [
      "npm run lint:fix",
      "npm run test:staged",
      "git add"
    ]
  },
```

**Comment by alex996** [comment]
Hmm, I tried changing index.ts and it auto-formatted it on commit.

**Comment by alex996** [comment]
From the readme, lint-staged uses micromatch for glob patterns. So, as long
as you pass a valid glob, it should work. You can check with
micromatch.isMatch() for example.
